### ISSUE TITLE
why does this repo exist

### ISSUE THREAD

**Issue by wgyt** [1hostjs/create-1host-app#1]
cc @GrahamSH-LLK

**Comment by GrahamSH-LLK** [comment]
I'm gonna make a version of create-nuxt-app for 1host

**Comment by wgyt** [comment]
ok, cool

**Comment by wgyt** [comment]
@GrahamSH-LLK wouldn't this be covered by the 1host cli, and more specifically 1host config?

**Comment by GrahamSH-LLK** [comment]
> @GrahamSH-LLK wouldn't this be covered by the 1host cli, and more specifically 1host config?

Yeah, I guess.
